### PR TITLE
List Multipart Uploads, List Parts

### PR DESCRIPTION
**Pull request by windkit**
#### Related Issue
leo-project/leofs#145

#### Current Status
Preliminary Implementation of `List Parts`
 - No Account Related Information, such as Initiator, Owner

#### Outcome
`boto` in `leofs_client_test` now can proceed for Multi Part Upload as it requires `List Parts`

### CODE REVIEW

**Comment by mocchira** [comment]
@windkit Thank you for the PR.

Two comments.

- NOT using ETS

Since there are some use cases where multiple leo_gateways co-exists and a load balancer in front of them, so ETS must be replaced with something which enable multiple leo_gateways to share multipart upload status between them.

Since adding some new system components to share status will make LeoFS design/architechture  complex, I and @yosukehara have considered using LeoFS itself as a multipart status holder.
Try this approach If you don't have any other alternatives.

- Take care that a multipart completion request might not be arrived at leo_gateway

due to client bugs or network partition.
So we need to have a something to clean up stale multipart upload status like garbage collectors.

**Comment by windkit** [comment]
Yes I understand the problem here, I am looking into how to implement it right.

One of the reasons I still put this preliminary solution is to see which information `boto` needs to complete Multipart Upload

@mocchira Concerning about your comment in leo-project/leofs#145 
```
...
Since LeoFS doesn't have enough information to realize this feature,
...
```
Could you elaborate more on that? Is it about the authentication information?

About the garbage collection, in Amazon S3 those stalling requests would just stay (and are charged $_$), are we going to provide a admin command for that?

**Comment by mocchira** [comment]
> Could you elaborate more on that? Is it about the authentication information?

Please don't worry about this line.
I'm also not sure what information are really needed for LeoFS unless I actually try it out.
So please go forward :)

> About the garbage collection, in Amazon S3 those stalling requests would just stay (and are charged $_$)

Wow I din't know that $_$ ...

> are we going to provide a admin command for that?

Yes we will. ( @yosukehara please point out if something wrong )

**Comment by windkit** [comment]
It seems using `Mnesia` to store related information on `leo_storage` nodes (`disc_copies`) could be a possible solution. Do you have any comments on that? @mocchira @yosukehara

**Comment by mocchira** [comment]
@windkit 
Since we are currently not using mnesia(disc_copies) on leo_storages, 
your approach is almost equivalent to adding the new DBMS(mnesia) on leo_storage.

So

* pros
 - Easy to implement CRUD logic with Erlang
 - Reasonable fast to access data
 - Able to use Transaction
 
* cons
 - Add complexity to the system
 - Increase operating cost to operate mnesia DBMS
 - Be more difficult to identify the performance issue on leo_storage
 - The largest table size is limited up to 4GB (http://www.erlang.org/faq/mnesia.html)

Pros/Cons will be inverted If you use LeoFS itself as a multipart status holder.

Thoughts?

**Comment by windkit** [comment]
Actually what I am thinking is to find a solution to save the mappings
`Bucket -> [UploadID]` and `UploadID -> [PartNumber]` backed with a persistent storage.

Using `mnesia` seems to be the easiest to implement and manage, 
 - `leo_storage` serve as persistent storage with `disc_copies / disc_only_copies`
 - `leo_gateway` serve queries with `ram_copies`

The mappings should be small enough to fit in the limit (just list of keys and it is temporary for each multiupload request) Actual binary data and metadata of parts would be kept as before, served with normal object interfaces.

Alternately, we can store information in bucket / object metadata. However I can't find interfaces for metadata-only operations and it would incur metadata layout changes, it is less favorable to me.

I think the major concern is about the overhead of maintaining a `mnesia` cluster which I am not sure about.

**Comment by mocchira** [comment]
> The mappings should be small enough to fit in the limit (just list of keys and it is temporary for 
> each multiupload request) Actual binary data and metadata of parts would be kept as before, 
> served with normal object interfaces.

Agreed.

> I think the major concern is about the overhead of maintaining a mnesia cluster which I am not sure about.

Yes. the overhead of maintaining a mnesia cluster could kill sysadmins who have not enough skill aboud DBMS and Erlang.

> Alternately, we can store information in bucket / object metadata. However I can't find interfaces 
> for metadata-only operations and it would incur metadata layout changes, it is less favorable to me.

Since we need to upgrade metadata layout when introducing erasure coding into LeoFS,
We can add some metadatas reasonably at that point.

**Comment by yosukehara** [comment]
[As Mocchira mentioned](https://github.com/leo-project/leo_gateway/pull/22#issuecomment-113431778), we need to consider ``a multipart status holder`` with LeoFS v1.4. After we reached the consensus about the design and architecture, we'll fix this issue.  So I've close your request.

**Pull request closed without merging**
