### PR TITLE
Implement NFSPROC3_READDIR based on NFSPROC3_READDIRPLUS

### PR DESCRIPTION
**Pull request by windkit**
### Purpose
To support FreeBSD NFS Client
 - Support READDIR operation in NFS, Current Implementation only includes a dummy holder
 - Include File Attributes in the reply of LOOKUP

### Description
READDIR works similarly to READDIRPLUS, except that file attributes are not returned
Essentially, READDIRPLUS = READDIR + GETATTRs

This PR basically copies the implementation from READDIRPLUS with file attributes ripped off.

### Related Issue
https://github.com/leo-project/leo_gateway/issues/27

### CODE REVIEW

**Comment by mocchira** [comment]
Since nfsproc3_readdir_3 is almost same with nfsproc3_readdirplus_3,
We can make it less verbose by making a common function and calling that from both of them.

**Comment by mocchira** [comment]
LGTM.
@windkit let me know if you have other updates.
if nothing, I'll merge.
(Please the another PR for SYNC delete)

**Comment by windkit** [comment]
I do not have updates at the moment, I will further test and create PR if necessary after SYNC delete.

I will move on to File Lock.

**Comment by mocchira** [comment]
@windkit FYI.
@yosukehara is now tackling on SYNC delete.
Could you check with the latest 1.4 build?
if there are still something wrong, please let us know.

**Comment by windkit** [comment]
@mocchira @yosukehara 
The recent commits on leo_storage seems targeting SYNC deletion of directory only, object deletion seems to be ASYNC.

Therefore, from my testing, it is OK to recursively delete multi-level directory tree when there are no files
```bash
$ mkdir -p dir1/dir2/dir3
$ rm -rf dir1
```

But it would fail when there are files. As the file is not marked as deleted at the first place.
Eventually the object would be "deleted", then it would back to the directory-only case.
```bash
$ mkdir -p dir11/dir12/dir13
$ touch dir11/dir12/dir13/file
$ rm -rf dir11
rm: dir11/dir12/dir13: Directory not empty
rm: dir11/dir12: Directory not empty
rm: dir11: Directory not empty
```

Anyway, I have to make some changes to handle sub-directories. I will create a new PR for that.

**Comment by yosukehara** [comment]
@windkit Actually, I've implemented the deletion of a directory, which is able to remove a directory w/synchronous processing but objects under the directory will be removed w/asynchronous processing because its processing need to spend much time.

I'll consider how do I implement that.

**Comment by yosukehara** [comment]
@windkit @mocchira I've implemented deletion of a directory and objects with synchronous w/latest leo_storage (1.4-branch). Do you think you could check that?

**Comment by windkit** [comment]
@yosukehara From my testing using "1.4.0-pre.2" for `leo_gateway`, `leo_storage`, `leo_manager`. The problem still remains.

Recursively deleting a directory can be broken down into three steps.

1. Get the list of files in the directory
2. Remove all the files accordingly
3. Remove the directory (Check if the directory is empty)

When step 2 is done asynchronously, the checking in step 3 would fail as it can still see those 'deleted' files

We probably need another code path for `leo_gateway_rpc_handler:delete` so we can keep async deletion for S3/REST but have sync delete for NFS 

#### Test
```bash
ubuntu1404s:/mnt/leofs$ mkdir -p layer1/layer2
ubuntu1404s:/mnt/leofs$ cp ~/jerasure.tar.gz layer1/layer2
ubuntu1404s:/mnt/leofs$ rm -rf layer1
rm: cannot remove ‘layer1/layer2’: Directory not empty
```
#### Log
```
[D]     gateway_0@127.0.0.1     2015-10-31 03:15:46.649387 -0700        1446286546      leo_nfs_proto3_server:nfsproc3_lookup_3 156     path:<<"test/layer1/layer2/jerasure.tar.gz">> client:{client,#Port<0.3969>,sock,3523381479,{'AUTH_NONE',<<>>}}
[D]     gateway_0@127.0.0.1     2015-10-31 03:15:46.650346 -0700        1446286546      leo_nfs_proto3_server:nfsproc3_remove_3 278     args:{{{<<"▒o▒▒`ICԫc^^▒W2▒">>},<<"jerasure.tar.gz">>}} client:{client,#Port<0.3969>,sock,3540158695,{'AUTH_NONE',<<>>}}
[D]     gateway_0@127.0.0.1     2015-10-31 03:15:46.652356 -0700        1446286546      leo_nfs_proto3_server:nfsproc3_access_3 173     path:<<"test/layer1">> mask:31 client:{client,#Port<0.3969>,sock,3556935911,{'AUTH_NONE',<<>>}}
[D]     gateway_0@127.0.0.1     2015-10-31 03:15:46.660190 -0700        1446286546      leo_nfs_proto3_server:nfsproc3_getattr_3        118     path:<<"test/layer1">> client:{client,#Port<0.3969>,sock,3573713127,{'AUTH_NONE',<<>>}}
[D]     gateway_0@127.0.0.1     2015-10-31 03:15:46.662083 -0700        1446286546      leo_nfs_proto3_server:nfsproc3_lookup_3 156     path:<<"test/layer1/layer2">> client:{client,#Port<0.3969>,sock,3590490343,{'AUTH_NONE',<<>>}}
[D]     gateway_0@127.0.0.1     2015-10-31 03:15:46.664048 -0700        1446286546      leo_nfs_proto3_server:nfsproc3_rmdir_3  291     args:{{{<<111,175,92,201,217,48,67,5,154,75,249,21,227,239,184,116>>},<<"layer2">>}} client:{client,#Port<0.3969>,sock,3607267559,{'AUTH_NONE',<<>>}}
[D]     gateway_0@127.0.0.1     2015-10-31 03:15:46.664963 -0700        1446286546      leo_nfs_proto3_server:is_empty_dir/1    475     List Dir <<"test/layer1/layer2/">>, [{metadata_2,<<"test/layer1/layer2/$$_dir_$$">>,33012858576551577069026823575322456192,0,0,0,0,1446286532028157,63613505731,0,0,0,0,0,undefined,0,0,copy,copy,undefined,undefined,0},{metadata_2,<<"test/layer1/layer2/jerasure.tar.gz">>,315709768345350039110522057419819422119,0,754544,0,0,1446286543813594,63613505743,0,958648327,0,0,0,undefined,0,0,copy,copy,undefined,undefined,0}]
```

**Comment by yosukehara** [comment]
@windkit Thanks for your comment. Actually, making a metadata into the dir-metadata layer w/async. I'll consider how I solve this issue, then fix that by LeoFS v1.4.0-pre3.

**Pull request merged**
